### ISSUE TITLE
the icons are gone?

### ISSUE THREAD

**Issue by sli1989** [theme-next/hexo-filter-optimize#2]
is it right?

```
filter_optimize:
  enable: true
  # remove static resource query string
  #   - like `?v=1.0.0`
  remove_query_string: true
  # remove the surrounding comments in each of the bundled files
  remove_comments: false
  css:
    enable: true
    # bundle loaded css file into the one
    bundle: true
    # use a script block to load css elements dynamically
    delivery: true
    # make specific css content inline into the html page
    #   - only support the full path
    #   - default is ['css/main.css']
    inlines:
    excludes:
  js:
    # bundle loaded js file into the one
    bundle: true
    excludes:
```

and then `hexo clean && hexo g && hexo s`
![_20180125153445](https://user-images.githubusercontent.com/8521181/35376349-b48a4820-01e5-11e8-9a79-c3d9469ba8d4.png)
